# Generated by Django 4.0.4 on 2022-06-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOptions',
        ),
        migrations.DeleteModel(
            name='PaymentSelections',
        ),
    ]
