# Generated by Django 4.0.4 on 2022-06-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_billing_status_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
